Repository googleapis/java-common-protos, pull requests merged in 2020-09, with the labels that each got.

#32 build: fix synth.py to generate only proto/grpc targets without gapic assembly tarball
  synth.py
Labels: cla: yes

#47 build(java): use yoshi-approver token for auto-approve
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#48 chore: add repo settings configuration
  .github/sync-repo-settings.yaml
Labels: automerge, cla: yes

#49 chore(ci): skip autorelease workflow on non-release PRs
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#50 chore(ci): verify autorelease release PR content has changes
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#51 chore(java): use separate autosynth job for README
  .github/readme/synth.py
  .kokoro/continuous/readme.cfg
  .kokoro/readme.sh
  synth.metadata
Labels: automerge, cla: yes, context: full
