Repository googleapis/java-common-protos, pull requests merged in 2021-09, with the labels that each got.

#217 chore: Add build langauge-specific targets for extended_operations.proto
  renovate.json
  synth.metadata
Labels: cla: yes, context: partial

#221 chore: remove readme autosynth config
  .github/readme/synth.py
  .kokoro/continuous/readme.cfg
Labels: cla: yes

#230 chore(java): remove dependencyDashboardLabel config from renovate.json
  renovate.json
  synth.metadata
Labels: cla: yes, context: full

#235 chore: change branch master to main in sync-repo-settings.yaml
  .github/sync-repo-settings.yaml
Labels: cla: yes

#234 chore: re-generated to pick up changes from synthtool
  .github/blunderbuss.yml
  .github/workflows/ci.yaml
  .kokoro/dependencies.sh
  synth.metadata
Labels: cla: yes, context: full

#236 chore: change branch master to main in github configurations
  README.md
Labels: automerge, cla: yes
