Repository googleapis/java-common-protos, pull requests merged in 2021-05, with the labels that each got.

#154 chore: remove unused variable
  pom.xml
Labels: cla: yes

#148 feat: Publish visibility.proto
  proto-google-common-protos/src/main/java/com/google/api/Authentication.java
  proto-google-common-protos/src/main/java/com/google/api/Endpoint.java
  proto-google-common-protos/src/main/java/com/google/api/EndpointOrBuilder.java
  proto-google-common-protos/src/main/java/com/google/api/Logging.java
  proto-google-common-protos/src/main/java/com/google/api/Service.java
  proto-google-common-protos/src/main/java/com/google/api/ServiceOrBuilder.java
  proto-google-common-protos/src/main/java/com/google/api/ServiceProto.java
  proto-google-common-protos/src/main/java/com/google/api/Visibility.java
  proto-google-common-protos/src/main/java/com/google/api/VisibilityOrBuilder.java
  proto-google-common-protos/src/main/java/com/google/api/VisibilityProto.java
  proto-google-common-protos/src/main/java/com/google/api/VisibilityRule.java
  proto-google-common-protos/src/main/java/com/google/api/VisibilityRuleOrBuilder.java
  synth.metadata
Labels: cla: yes, context: partial

#151 chore: adding cloud-rad java xrefs
  .github/release-please.yml
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: automerge, cla: yes, context: partial

#161 build(java): remove codecov action
  .github/workflows/ci.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#172 chore: start tracking obsolete files
  synth.metadata
Labels: automerge, cla: yes, context: full

#176 chore: remove duplicate copies of protos
  proto-google-common-protos/src/main/proto/google/api/attribute_context.proto
  proto-google-common-protos/src/main/proto/google/api/audit_log.proto
  proto-google-common-protos/src/main/proto/google/api/calendar_period.proto
  proto-google-common-protos/src/main/proto/google/api/code.proto
  proto-google-common-protos/src/main/proto/google/api/color.proto
  proto-google-common-protos/src/main/proto/google/api/date.proto
  proto-google-common-protos/src/main/proto/google/api/datetime.proto
  proto-google-common-protos/src/main/proto/google/api/dayofweek.proto
  proto-google-common-protos/src/main/proto/google/api/decimal.proto
  proto-google-common-protos/src/main/proto/google/api/error_details.proto
  proto-google-common-protos/src/main/proto/google/api/expr.proto
  proto-google-common-protos/src/main/proto/google/api/fraction.proto
  proto-google-common-protos/src/main/proto/google/api/http_request.proto
  proto-google-common-protos/src/main/proto/google/api/interval.proto
  proto-google-common-protos/src/main/proto/google/api/latlng.proto
  proto-google-common-protos/src/main/proto/google/api/localized_text.proto
  proto-google-common-protos/src/main/proto/google/api/log_severity.proto
  proto-google-common-protos/src/main/proto/google/api/money.proto
  proto-google-common-protos/src/main/proto/google/api/month.proto
  proto-google-common-protos/src/main/proto/google/api/operations.proto
  proto-google-common-protos/src/main/proto/google/api/phone_number.proto
  proto-google-common-protos/src/main/proto/google/api/postal_address.proto
  proto-google-common-protos/src/main/proto/google/api/quaternion.proto
  proto-google-common-protos/src/main/proto/google/api/status.proto
  proto-google-common-protos/src/main/proto/google/api/timeofday.proto
  proto-google-common-protos/src/main/proto/google/api/viewport.proto
  synth.py
Labels: automerge, cla: yes
